services:
  backend:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_db:/chroma_db
      - ./src/api:/app
      - ./.env:/app/.env

  frontend:
    build:
      context: .
      dockerfile: src/app/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./chroma_db:/chroma_db
      - ./src/app:/app
      - ./.env:/app/.env  # Mount the .env file from root to the container

    depends_on:
      - backend